# updated regex to handle quebec variations...
ROIS = [ "EXT", "GTV", "ALLCTV", "LOWRCTV", "MIDRCTV", "HIGHRCTV", "NODES",
         "LNECK", "RNECK", "BSTEM", "ESOPH", "LARYNX", "POSTCRI", "CHIASM",
         "LLAC", "RLAC", "LLENS", "RLENS", "LEYE", "REYE", "LOPTIC", "ROPTIC",
         "LPAR", "RPAR", "TRAC", "SPCOR", "MAND", "LSMAN", "RSMAN", "LACOU",
         "RACOU", "LCHAMBER", "RCHAMBER", "LIPS", "RRETRO", "LRETRO", "LPLEX",
         "RPLEX", "BRAIN", "PIT", "OCAV", "IPCM", "SPCM", "MPCM", "THYR", "MRETRO",
         "SKIN", "SPHNC", "LMEAR", "RMEAR"]

mastro = ["EXT", "GTV", "BSTEM", "RSMAN", "LSMAN", "LARYNX", "MAND", "SPCOR", "REYE", "LEYE", "ROPTIC",
          "LOPTIC", "RLENS", "LLENS", "CHIASM", "THYROID", "SKIN", "RACOU", "LACOU"]

mastro_regex = ["CIALO", "GTV", "PIEN", "SLINIANKA( |)((\(|)P(\)|))","SLINIANKA( |)((\(|)L(\)|))","KRTAN","ZUCHWA",
                "RDZEN( |_)KREGOWY", "OKO( |)((\(|)P(\)|))", "OKO( |)((\(|)L(\)|))",
                "NERW WZROK(.|)( |)((\(|)P(\)|))", "NERW WZROK(.|)( |)((\(|)L(\)|))",
                "SOCZEWKA(.|)( |)((\(|)P(\)|))", "SOCZEWKA(.|)( |)((\(|)L(\)|))",
                "CHIASM(A|)", "TARCZYCA", "SKORA","UCHO(.|)( |)((\(|)P(\)|))", "UCHO(.|)( |)((\(|)L(\)|))"]

sccgen = ["RETROP","MEDOB","SPCOR", "BRAIN","RACOU","LACOU","RPAR", "LPAR", "RSMAN","LSMAN",
          "RNECK", "LNECK", "GTV-1", "GTV-2", "GTV-3", "GTV-4", "GTV-5", "GTV-6", "GTV-7",
          "GTV-8","GTV-9","GTV-10", "LUNG-RIGHT","LUNG-LEFT","ESOPHAGUS","LUNGS-TOTAL", "HEART"]

cgenregex = ["RETROPHARYNX","MEDULLA-OBLONGATA","SPINAL-CORD","BRAIN","COCHLEA-RIGHT","COCHLEA-LEFT",
             "PAROTID-RIGHT","PAROTID-LEFT","SUBMANDIBULAR-GLAND-RIGHT","SUBMANDIBULAR-GLAND-LEFT",
             "NECK-RIGHT","NECK-LEFT", "GTV-1", "GTV-2", "GTV-3", "GTV-4", "GTV-5", "GTV-6", "GTV-7",
             "GTV-8", "GTV-9", "GTV-10", "LUNG-RIGHT","LUNG-LEFT","ESOPHAGUS","LUNGS-TOTAL", "HEART"]

cgenregex2 = ["RETROPHARYNX","MEDULLA-OBLONGATA","SPINAL-CORD","BRAIN","COCHLEA-RIGHT","COCHLEA-LEFT",
             "PAROTID-RIGHT","PAROTID-LEFT","SUBMANDIBULAR-GLAND-RIGHT","SUBMANDIBULAR-GLAND-LEFT",
             "NECK-RIGHT","NECK-LEFT", "GTV((-|_)|)1((_|-)|)((R|L)(E|)|)", "GTV((-|_)|)2((_|-)|)((R|L)(E|)|)",
             "GTV((-|_)|)3((_|-)|)((R|L)(E|)|).*", "GTV((-|_)|)4((_|-)|)((R|L)(E|)|)", "GTV((-|_)|)5((_|-)|)((R|L)(E|)|)",
             "GTV((-|_)|)(6|R)((_|-)|)((R|L)(E|)|)", "GTV((-|_)|)(NR(_|)|)7((_|-)|)((R|L)(E|)|)", "GTV((-|_)|)8((_|-)|)((R|L)(E|)|)",
             "GTV((-|_)|)9((_|-)|)((R|L)(E|)|)", "GTV((-|_)|)10((_|-)|)((R|L)(E|)|)", "LUNG-RIGHT","LUNG-LEFT",
             "ESOPHAGUS","SPINAL-CORD", "LUNGS-TOTAL", "HEART"]

REGEX = [
    "(EX.ERNAL|BODY)",
    "GTV(P|)", # "(GTV|IGTV)(( |)(1|70)|)(([-]|)(P|)(.|)([6-7][0-9]([.]|)([5]|)|1)(GY|)|)",
    "CTV( |(P|_))*[4-7][0-9]*",
    "CTV(( |P)|)([4][6-9]|[5][0-6])*([0](.|)|)(2|)(([-]|[_])|)(([4][6-9]|[5][0-6])|)([0](.|)|)((GY|P)|(Y|))",
    "CTV(( |P)|)([5][7-9]|[6][0-6])*([0](.|)|)(2|)(([-]|[_])|)(([5][7-9]|[6][0-6])|)([0](.|)|)((GY|P)|(Y|))",
    "CTV(( |P)|)([6][7-9]|[7][0-6])*([0](.|)|)(1|)(([-]|[_])|)(([6][7-9]|[7][0-6])|)([0](.|)|)((GY|P)|(Y|))",
    "(I|[1-9])* *(L|R)*(A|B)* *([1-9]|(A|B))*",
    "(L(EFT|)|)(NECK|CTV)(-|)( *|(P|_))( *|[4-7][0-9])(L(EFT|)|)",
    "(R(IGHT|)|)(NECK|CTV)(-|)( *|(P|_))( *|[4-7][0-9])(R(IGHT|)|)",
    "(B*((R| )|AIN| )* *STEM|TR(ONC|)(( |.)|)(CEREBRAL|))",
    "((O|E)| )*ESOPHAG(US|E).*",
    "(CARTILAGE|)(GLOTTI(C|S)|(T|)VC*)* *((ENDO|)LARYNX|)(|\(SP\))",
    "(POST|)* *(C(R|)ICO(I|R)D|POSTERIOR)",
    "(?!PRV)(OPT(IC|)| )*C(H|)IASM(.|)(|OPTIC)",
    "((((L|LT)(.|)|)LAC(.|)IMAL.|)((GLAND|GL)| )*|(LACRIMAL_L|(LACR(Y|)(MALE|)|( |))((GCHE|G)|((L|LT)|))))",
    "((((R|RT)(.|)|)LAC(.|)IMAL.|)((GLAND|GL)| )*|(LACRIMAL_R|(LACR(Y|)(MALE|)|( |))((DRT|D)|((R|RT)|))))",
    "((L(T|)(.|( |))LENS(.|)|LENS( |)(.|)L(.|))|CRISTAL((L|)IN|)(.|)(G(CHE|)|))",
    "((R(T|)(.|( |))LENS(.|)|LENS( |)(.|)L(.|))|CRISTAL((L|)IN|)(.|)(D(RT|)|))",
    "(?!R)(((.|)L(T|(.|))(.|)|)((EYE|OEIL)|(GLOBE|ORBIT))((( |).|)L|)(.|))(G(CHE|)|)( |)(([0-9])|)",
    "(?!L)(((.|)R(T|(.|))(.|)|)((EYE|OEIL)|(GLOBE|ORBIT))((( |).|)R|)(.|))(D(RT|)|)( |)(([0-9])|)",
    "(?!R)(L|)(NERF|)(.|)( |)OPT(I(C|QUE)|)( |)(G(CHE|)|)(N(E|)(RV|)(E|)|)( |)(([(]|_)|)(L|)(T|)([)]|)",
    "(?!L)(R|)(NERF|)(.|)( |)OPT(I(C|QUE)|)( |)(D(RT|)|)(N(E|)(RV|)(E|)|)( |)(([(]|_)|)(R|)(T|)([)]|)",
    "(?!R)(L(T|)|)(.|)PAR(O|)((T|OT)|(TOT|))(ID|)(E|)(( |)((_|1)|)|)((.|)L(.|)|G(CHE|)|)",
    "(?!L)(R(T|)|)(.|)PAR(O|)((T|OT)|(TOT|))(ID|)(E|)(( |)((_|1)|)|)((.|)R(.|)|D(RT|)|)",
    "T(RA|AR)CH(E(A|)|)",
    "(SPIN(E|AL)(.|)|( |))((C(ORD|ANAL)|)|MOELLE)",
    "(PP|)MANDIB(U|)LE( .|)",
    "((L.* *SUB.*|SUB.*L(EFT|))(.|)|GLANDE SM G((CHE|AUCHE)|))",
    "((R.* *SUB.*|SUB.*R(IGHT|))(.|)|GLANDE SM D((RT|ROITE)|))",
    "(?!R)((.|)L.( |)|)((AC(OUS|OSU)TIC|AUDITORY)|(( |)(COCHLE(A|E)|OREILLE)((-|_)|( |))(L(T|)(EFT|)|)|(EAR(.|)|)((INNER|INTERNAL)|)(( |)EAR|))(( |)(.|)(GCHE|(.(INT).|)G)|))",
    "(?!L)((.|)R.( |)|)((AC(OUS|OSU)TIC|AUDITORY)|(( |)(COCHLE(A|E)|OREILLE)((-|_)|( |))(R(T|)(IGHT|)|)|(EAR(.|)|)((INNER|INTERNAL)|)(( |)EAR|))(( |)(.|)(DRT|(.(INT).|)D)|))",
    "(L.*| *ANT)* *CHAMBER.*",
    "(R.*| *ANT)* *CHAMBER.*",
    "(LIP|LEVRE)(S|)(PHYS|)* *((FOR|IN|BY.*|AWAY.*|AVOID)|(LXC|SS)| *SPAR(E|ING))*",
    "(I*)(R( |)RP(N|)|(R.*RETRO.*|RETRO_R))",
    "(I*)(L( |)RP(N|)|(L.*RETRO.*|RETRO_L))",
    "(?!R)((.|)L(.|)|)PL(EXUS|)( |)(BRAC(HIAL|)|)( |)(G(CHE|)|)((.|)L(.|)|)(1|)",
    "(?!L)((.|)R(.|)|)PL(EXUS|)( |)(BRAC(HIAL|)|)( |)(D(RT|)|)((.|)R(.|)|)(1|)",
    "(BR(AIN|3)|CERVEAU)(.|)(?!CF)",
    "PITUITA(IRE|RY).*",
    "((MOUTH(.|)|)(ORAL.*CAVITY.|ORAL.*)|CAVITE.*ORAL.*)",
    "((I(UP|P)C|INFERIOR CONSTRICTORS)|)((MUSCLE|MUSC_CONSTRICT_I)|)",
    "(S(UP|P)C|)((MUSCLE|MUSC_CONSTRICT_S)|)",
    "(M(UP|P)C|)((MUSCLE|MUSC_CONSTRICT_M)|)",
    "THYROID(E|)( |)(GLAND|)",
    "(M|)( |)RETROPHARYNGES",
    "(SKIN|PEAU)",
    "SPHINCTER( |)MUSCLE",
    "(?!R)(( |)([(]|)L(.|)( |)|)((AC(OUS|OSU)TIC|AUDITORY)|(( |)(OREILLE)|(EAR(.|)|)((MID(DLE|)(.|))|)(( |)EAR|))(( |)(.|)(G(CHE|)|(.(MOY).|)G(CHE|))|))",
    "(?!L)(( |)([(]|)R(.|)( |)|)((AC(OUS|OSU)TIC|AUDITORY)|(( |)(OREILLE)|(EAR(.|)|)((MID(DLE|)(.|))|)(( |)EAR|))(( |)(.|)(D(RT|)|(.(MOY).|)D(RT|))|))"
]

og_regex = [
    "EX.ERNAL",
    "(GTV|IGTV)*",
    "CTV( |(P|_))*[4-7][0-9]*",
    "CTV( |(P|_))*([4][6-9]|[5][0-6])*([0][0]| *)",
    "CTV( |(P|_))*([5][7-9]|[6][0-6])*([0][0]| *)",
    "CTV( |(P|_))*([6][7-9]|[7][0-6])*([0][0]| *)",
    "(I|[1-9])* *(L|R)*(A|B)* *([1-9]|(A|B))*",
    "L(NECK|CTV)( *|(P|_))( *|[4-7][0-9])",
    "R(NECK|CTV)( *|(P|_))( *|[4-7][0-9])",
    "(B*((R| )|AIN| )* *STEM|MEDULLA-OBLONGATA)",
    "((O|E)| )*ESOPHAGUS.*",
    "(GLOTTI(C|S)|(T|)VC*)* *((ENDO|)LARYNX|)(|\(SP\))",
    "(POST|)* *(C(R|)ICO(I|R)D|POSTERIOR)",
    "(OPT(IC|)| )*C(H|)IASM*(.|)*(|OPTIC)",
    "(L.* *LAC(.|)IMAL.* *(GLAND| )*|LACRIMAL_L)",
    "(R.* *LACRIMAL.* *(GLAND| )*|LACRIMAL_R)",
    "(L.* *LENS.*|LENS_L)",
    "(R.* *LENS.*|LENS_R)",
    "(L.* *(EYE|(GLOBE|ORBIT)).*|EYE(_|( |))L)",
    "(R.* *(EYE|(GLOBE|ORBIT)).*|EYE(_|( |))R)",
    "(L.*OPTIC( *NERVE*)*|OPTICNRV_L)",
    "(R.*OPTIC( *NERVE*)*|OPTICNRV_R)",
    "((L|).* *PAR((T|OT)|TOT)ID.*|PAROTID(_|-)L(EFT|))",
    "((R|).* *PAR((T|OT)|TOT)ID.*|PAROTID(_|-)R(IGHT|))",
    "T(RA|AR)CH(E(A|)|)",
    "(SPIN(E|AL).*|( |))(C(ORD|ANAL)|)",
    "(PP|)MANDIBLE.*",
    "(L.* *SUB.*|SUB.*L)",
    "(R.* *SUB.*|SUB.*R)",
    "(L.*|)((AC(OUS|OSU)TIC|AUDITORY)|(COCHLEA|(EAR.|)INNER(EAR|)))(.L|)",
    "(R.*|)((AC(OUS|OSU)TIC|AUDITORY)|(COCHLEA|(EAR.|)INNER(EAR|)))(.R|)",
    "(L.*| *ANT)* *CHAMBER.*",
    "(R.*| *ANT)* *CHAMBER.*",
    "LIP(S|)* *((FOR|IN|BY.*|AWAY.*|AVOID)|(LXC|SS)| *SPAR(E|ING))*",
    "(I*)(R( |)RP(N|)|(R.*RETRO.*|RETRO_R))",
    "(I*)(L( |)RP(N|)|(L.*RETRO.*|RETRO_L))",
    "(R( |)|)(BRACHIAL( |)|)(PLEX(US|)(_R|)|)",
    "(L( |)|)(BRACHIAL( |)|)(PLEX(US|)(_L|)|)",
    "BR(AIN|3).*",
    "PITUITARY.*",
    "(ORAL.*CAVITY.|ORAL.*)",
    "((I(UP|P)C|INFERIOR CONSTRICTORS)|)((MUSCLE|MUSC_CONSTRICT_I)|)",
    "(S(UP|P)C|)((MUSCLE|MUSC_CONSTRICT_S)|)",
    "(M(UP|P)C|)((MUSCLE|MUSC_CONSTRICT_M)|)",
]
